# Generated by Django 4.2.7 on 2024-01-01 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('remark', models.CharField(default='', max_length=200)),
                ('category', models.CharField(choices=[('Cash In', 'Cash In'), ('Cash Out', 'Cash Out')], max_length=100, null=True)),
                ('expense_type', models.CharField(choices=[('Food', 'Food'), ('School', 'School'), ('Church', 'Church'), ('Personal', 'Personal')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
