# Generated by Django 4.2.7 on 2024-01-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_type',
            new_name='type_of_expense',
        ),
    ]
