# Generated by Django 4.2.7 on 2024-01-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0002_rename_expense_type_expense_type_of_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('School', 'School'), ('Church', 'Church'), ('Personal', 'Personal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type_of_expense',
            field=models.CharField(choices=[('Cash In', 'Cash In'), ('Cash Out', 'Cash Out')], max_length=100, null=True),
        ),
    ]
